# Generated by Django 3.0.2 on 2020-04-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
