# Generated by Django 3.0.2 on 2020-04-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200403_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subject',
            field=models.CharField(blank=True, choices=[('workout', 'workout'), ('nutrition', 'nutrition'), ('massages', 'massages'), ('other', 'other')], max_length=100),
        ),
    ]
