# Generated by Django 3.0.2 on 2020-04-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20200403_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='thumb',
            field=models.ImageField(blank=True, default='1.jpg', null=True, upload_to=''),
        ),
    ]
